-- Store settings singleton columns (MySQL)
CREATE TABLE IF NOT EXISTS store_settings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre_comercial VARCHAR(150) NULL,
  razon_social VARCHAR(200) NULL,
  rtn VARCHAR(50) NULL,
  direccion VARCHAR(255) NULL,
  telefono VARCHAR(50) NULL,
  correo VARCHAR(255) NULL,
  logo_url VARCHAR(500) NULL,
  moneda VARCHAR(10) NOT NULL DEFAULT 'HNL',
  isv_rate DECIMAL(10,2) NOT NULL DEFAULT 15.00,
  prices_include_isv TINYINT(1) NOT NULL DEFAULT 1,
  legal_text TEXT NULL,
  cai VARCHAR(100) NULL,
  rango_desde VARCHAR(50) NULL,
  rango_hasta VARCHAR(50) NULL,
  fecha_vencimiento_cai DATETIME NULL,
  establecimiento VARCHAR(50) NULL,
  punto_emision VARCHAR(50) NULL,
  correlativo_actual INT UNSIGNED NOT NULL DEFAULT 1,
  card_surcharge_rate DECIMAL(10,2) NULL DEFAULT 0,
  discount_limit_cashier DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount_limit_supervisor DECIMAL(10,2) NOT NULL DEFAULT 20,
  discount_limit_admin DECIMAL(10,2) NOT NULL DEFAULT 100,
  layaway_days_max INT UNSIGNED NOT NULL DEFAULT 8,
  layaway_min_down_payment_amount DECIMAL(10,2) NULL DEFAULT 0,
  layaway_min_down_payment_percent DECIMAL(10,2) NULL DEFAULT 0,
  loyalty_point_value DECIMAL(10,2) NOT NULL DEFAULT 1.0,
  loyalty_earn_rate_points INT UNSIGNED NOT NULL DEFAULT 1,
  loyalty_earn_rate_lempiras DECIMAL(10,2) NOT NULL DEFAULT 10,
  loyalty_allow_pay_with_points TINYINT(1) NOT NULL DEFAULT 1,
  loyalty_allow_mixed_payment TINYINT(1) NOT NULL DEFAULT 1,
  loyalty_max_points_percent_per_sale DECIMAL(10,2) NOT NULL DEFAULT 80,
  loyalty_min_redeem_amount DECIMAL(10,2) NOT NULL DEFAULT 10,
  loyalty_topup_min DECIMAL(10,2) NOT NULL DEFAULT 50,
  loyalty_topup_max DECIMAL(10,2) NOT NULL DEFAULT 5000,
  loyalty_topup_allowed_methods TEXT NOT NULL,
  loyalty_topup_earns_points TINYINT(1) NOT NULL DEFAULT 0,
  store_hours TEXT NULL,
  low_stock_threshold INT UNSIGNED NOT NULL DEFAULT 5,
  multi_branch_enabled TINYINT(1) NOT NULL DEFAULT 0
);

ALTER TABLE store_settings
  ADD COLUMN IF NOT EXISTS nombre_comercial VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS razon_social VARCHAR(200) NULL,
  ADD COLUMN IF NOT EXISTS direccion VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS telefono VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS correo VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS moneda VARCHAR(10) NOT NULL DEFAULT 'HNL',
  ADD COLUMN IF NOT EXISTS legal_text TEXT NULL,
  ADD COLUMN IF NOT EXISTS rango_desde VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS rango_hasta VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS fecha_vencimiento_cai DATETIME NULL,
  ADD COLUMN IF NOT EXISTS establecimiento VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS punto_emision VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS correlativo_actual INT UNSIGNED NOT NULL DEFAULT 1;

INSERT INTO store_settings (id) VALUES (1)
ON DUPLICATE KEY UPDATE id = VALUES(id);
